sudo: false
language: node_js
node_js:
- 10
cache: yarn
branches:
  only:
  - master
install:
- yarn install
script:
- yarn build
after_success:
- mkdir dist
- cp -r .next/ dist/.next
- cp package.json dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  target_branch: DEPLOY-PROD
  committer_from_gh: true
  on:
    branch: master
  local_dir: dist
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
